#!/bin/bash

mkdir src
cp -r ../CMSIS-DSP/* .
cp -r Include/* src
cp -r PrivateInclude/* src
cp -r Source src
find  src/Source/ -type d | sed 's|src/Source/||g' | xargs -I{} rm src/Source/{}/{}.c
#Functions provided as .S for maximum speed
#rm src/Source/TransformFunctions/arm_bitreversal2.c
